language: cpp

sudo: required

os:
  - linux

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-dev libboost-test-dev libboost-program-options-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev
  - sudo apt-get install -y -qq git
  - cd /tmp
  - git clone https://github.com/apache/thrift.git
  - cd thrift
  - git checkout 0.9.1
  - ./bootstrap.sh
  - ./configure --with-ruby=no --with-go=no --with-java=no
  - make
  - sudo make install
  - cd /tmp/thrift/contrib/fb303
  - ./bootstrap.sh
  - ./configure
  - make
  - sudo make install

install:
  - ./configure CPPFLAGS="-DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -DBOOST_FILESYSTEM_VERSION=2" LIBS="-lboost_system -lboost_filesystem"
  - make
  - sudo make install